mongodb:
  database: test
  username: "grafanaro"
  password: "EssplDB1997"
  clusterEndpoint: "docdb-2026-01-06-06-21-53.cfocyuk6aet4.ap-south-1.docdb.amazonaws.com:27017"
  readPreference: "secondaryPreferred"
  truststore: "rds-truststore.jks"
  truststorePassword: "EssplDB1997"

prometheus:
  port: 9091
  endpoint: /metrics
  jobName: mongo_metrics
  
metrics:
  - name: users_count_gt_32
    help: "Total Users count age greater than 32"
    collection: userdata
    placeholders:
      oneHourAgo: "new java.text.SimpleDateFormat(\"yyyy-MM-dd'T'HH:mm:ss'Z'\").format(new java.util.Date(System.currentTimeMillis() - 3600000))"
    query: |
      [
        {
          $match: {
            createdAt: { 
              $gte: ISODate("{{oneHourAgo}}") 
            }
          }
        },
        {
          $count: "total"
        }
      ]
    type: gauge
    field: total
    groupLabel:
    staticlabels:
      server: docdb-2026-01-06-06-21-53.cfocyuk6aet4.ap-south-1.docdb.amazonaws.com
      database: test
      collection: userdata
      criteria: age_gt_32
  - name: Total_users_Tom_Cruise
    help: "Total users in the collection by name Tom Cruise"
    collection: users
    placeholders:
      dummy: "1+1"
    query: |
      [
        {
          $match: {
            name: "Tom Cruise"
          }
        },
        {
          $count: "total"
        }
      ]
    type: gauge
    field: total
    groupLabel: 
    staticlabels:
      server: docdb-2026-01-06-06-21-53.cfocyuk6aet4.ap-south-1.docdb.amazonaws.com
      database: test
      collection: users
      criteria: name_Tom_Cruise
